version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "${BACKEND_PORT}:3000"
    volumes:
      - ./backend:/app
    environment:
      - NODE_ENV=development
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "${FRONTEND_PORT}:80"
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=development
    networks:
      - app-network

  db:
    image: postgres
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
